In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.5.3


Scalar

In [2]:
x = np.array(5)
print(x)
print("shape: ", x.shape)
print('dimensions: ', x.ndim)

5
shape:  ()
dimensions:  0


Vector

In [3]:
x = np.array([1, 2, 3, 4])
print(x)
print("shape: ", x.shape)
print("dimensions: ", x.ndim)

[1 2 3 4]
shape:  (4,)
dimensions:  1


In [4]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(x)
print('shape: ', x.shape)
print('dimensions: ', x.ndim)

[[1 2 3]
 [4 5 6]]
shape:  (2, 3)
dimensions:  2


In [5]:
x = np.array([
    [
        [1, 2],
        [3, 4]
    ],
    [
        [5, 6],
        [7, 8]
    ]
])
print(x)
print('shape: ', x.shape)
print('dimensions: ', x.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape:  (2, 2, 2)
dimensions:  3


In [8]:
x = np.array([
    [10,20,30],
    [40,50,60]
])
print(x[0,0])
print(x[0,1])
print(x[1,2])

10
20
60


In [11]:
x = np.array([1, 2, 3, 4, 5])
print(x * 10)
print(x + 10)
print(x ** 2)

[10 20 30 40 50]
[11 12 13 14 15]
[ 1  4  9 16 25]


In [12]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])

In [13]:
C = A @ B
print(C)

[[19 22]
 [43 50]]


In [14]:
A = np.array([
    [1, 2],
    [3, 4]
])

B = np.array([
    [5, 6],
    [7, 8]
])
print("A shape:", A.shape)
print("B shape:", B.shape)
print("A @ B shape:", (A @ B).shape)

A shape: (2, 2)
B shape: (2, 2)
A @ B shape: (2, 2)


In [16]:
import numpy as np

x = np.random.rand(3, 4)

print(x)
print("Shape: ", x.shape)
print("Dimensions: ", x.ndim)
print("Data type: ", x.dtype)

[[0.52302947 0.22128021 0.34342543 0.39065545]
 [0.97940245 0.37875625 0.316524   0.05643511]
 [0.39727153 0.8468115  0.03735838 0.17238665]]
Shape:  (3, 4)
Dimensions:  2
Data type:  float64
