In [1]:
import torch
print("PyTorch version:", torch.__version__)

PyTorch version: 2.14.0+cpu


In [2]:
x = torch.tensor([1,2,3,4])
print(x)
print("Shape: ", x.shape)
print("Dimensions: ", x.ndim)
print("Dtype: ", x.dtype)

tensor([1, 2, 3, 4])
Shape:  torch.Size([4])
Dimensions:  1
Dtype:  torch.int64


In [3]:
x = torch.tensor([
    [1,2,3],
    [4,5,6]
])
print(x)
print("Shape: ", x.shape)
print('Dimensions: ', x.ndim)

tensor([[1, 2, 3],
        [4, 5, 6]])
Shape:  torch.Size([2, 3])
Dimensions:  2


In [4]:
x = torch.tensor([1.0, 2.0, 3.0])

print(x)
print(x.dtype)

tensor([1., 2., 3.])
torch.float32


In [6]:
x = torch.tensor([1.0, 2.0, 3.0])
print(x + 10)
print(x * 2)
print(x ** 2)

tensor([11., 12., 13.])
tensor([2., 4., 6.])
tensor([1., 4., 9.])


In [7]:
A = torch.tensor([
    [1.0, 2.0],
    [3.0, 4.0]
])

B = torch.tensor([
    [5.0, 6.0],
    [7.0, 8.0]
])
C = A @ B
print(C)

tensor([[19., 22.],
        [43., 50.]])


In [9]:
x = torch.tensor([1.0, 2.0, 3.0])
print(x.device)

cpu


In [10]:
device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)
print(device)

cpu


In [11]:
x = torch.tensor([1.0, 2.0, 3.0]).to(device)
print(x)
print(x.device)

tensor([1., 2., 3.])
cpu


In [17]:
import numpy as np
import torch

np_array = np.array([1, 2, 3])

tensor = torch.from_numpy(np_array)

print(np_array)
print(tensor)

[1 2 3]
tensor([1, 2, 3])


In [13]:
torch = torch.tensor([1,2,3])
np_array = torch.numpy()
print(tensor)
print(np_array)

tensor([1, 2, 3])
[1 2 3]


In [19]:
import torch
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2
y.backward()
print("x:", x)
print("y:", y)
print("gradient:", x.grad)

x: tensor(3., requires_grad=True)
y: tensor(9., grad_fn=<PowBackward0>)
gradient: tensor(6.)


In [20]:
weight = torch.tensor(2.0, requires_grad=True)

x = torch.tensor(3.0)
target = torch.tensor(10.0)

prediction = weight * x

loss = (prediction - target) ** 2
loss.backward()

print("Prediction: ", prediction)
print("Loss: ", loss)
print("Weight gradient: ", weight.grad)

Prediction:  tensor(6., grad_fn=<MulBackward0>)
Loss:  tensor(16., grad_fn=<PowBackward0>)
Weight gradient:  tensor(-24.)


In [21]:
import torch
import torch.nn as nn
model = nn.Sequential(
    nn.Linear(2, 4),
    nn.ReLU(),
    nn.Linear(4, 1)
)
print(model)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): ReLU()
  (2): Linear(in_features=4, out_features=1, bias=True)
)


In [24]:
total_parameters = sum(
    p.numel() for p in model.parameters() 
)
print("Total parameters: ", total_parameters)

Total parameters:  17


In [25]:
import torch

print("=" * 40)
print("PyTorch Environment")
print("=" * 40)

print("PyTorch version :", torch.__version__)
print("CUDA available :", torch.cuda.is_available())

device = torch.device(
    "cuda" if torch.cuda.is_available() else "cpu"
)

print("Selected device :", device)

x = torch.randn(3,4).to(device)

print("Tensor shape :", x.shape)
print("Tensor dtype :", x.dtype)
print("Tensor device :", x.device)

PyTorch Environment
PyTorch version : 2.14.0+cpu
CUDA available : False
Selected device : cpu
Tensor shape : torch.Size([3, 4])
Tensor dtype : torch.float32
Tensor device : cpu
